name: expense_tracker
description: A beautiful offline-first expense tracker for iOS
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  image_picker: ^1.0.4
  fl_chart: ^0.64.0
  csv: ^6.0.0
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.6
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
